apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-cards
  name: user-cards-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-cards
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-cards
    spec:
      containers:
      - env:
        - name: DATABASE_IP
          valueFrom:
            configMapKeyRef:
              key: DATABASE_IP
              name: card-matching-cluster-configmap
        - name: OAUTH_SIGN_KEY
          valueFrom:
            configMapKeyRef:
              key: OAUTH_SIGN_KEY
              name: card-matching-cluster-configmap
        - name: OAUTH_TOKEN_PROVIDER
          valueFrom:
            configMapKeyRef:
              key: OAUTH_TOKEN_PROVIDER
              name: card-matching-cluster-configmap
        image: cardmatching/user-cards:latest
        name: user-cards
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /health/live
            port: server
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: server
          initialDelaySeconds: 10
          periodSeconds: 3
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: user-cards
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: user-cards