name: package fastAPI app as Docker image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        timeZone: 1
        format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKERHUB_BOT_USERNAME }}
       password: ${{ secrets.DOCKERHUB_BOT_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: cardmatching/user-cards:${{ steps.time.outputs.time }},cardmatching/user-cards:latest
